- name: "Check if migration {{ cam_migration_name }} is completed"
  k8s_facts:
    kind: MigMigration
    api_version: v1alpha1
    namespace: "{{ cam_ns }}"
    name: "{{ cam_migration_name }}"
  register: mig_phase
  until: mig_phase.resources[0].get("status", {}).get("phase", "") in 'Completed'
  retries: 120
  delay: 10

- name: "Mark migration end"
  set_fact:
    mig_end: "{{ lookup('pipe', 'date \"+%F %T\"') }}"

- set_fact:
    mig_elapsed_time: "{{ ((mig_end | to_datetime) - (mig_start | to_datetime)).total_seconds() }}"

- name: "Print migration elapsed time"
    msg: "Total migration time in seconds: {{ mig_elapsed_time }}s"
